"""initial tables

Revision ID: 4d77420cb242
Revises: 
Create Date: 2026-05-24 19:41:56.587938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4d77420cb242'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lastmile_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picking_rank', sa.Integer(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('mapping', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('date_last_refresh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slugs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.Column('seo_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('global_category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('global_category_parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lastmile_products',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraint_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_to_kg', sa.Float(), nullable=False),
    sa.Column('conversion_value', sa.Float(), nullable=False),
    sa.Column('country_of_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deposit_price', sa.Float(), nullable=False),
    sa.Column('dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_nutritions', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_fixed_weight', sa.Boolean(), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('last_month_lowest_price', sa.Float(), nullable=False),
    sa.Column('maximum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('promo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promo_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slugs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('standard_order_quantity', sa.Integer(), nullable=False),
    sa.Column('store_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_weight', sa.Float(), nullable=False),
    sa.Column('name_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allergens', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storing_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safety_information', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nutrition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comparative_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'store')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('lastmile_products')
    op.drop_table('lastmile_categories')
    # ### end Alembic commands ###
