"""initial tables

Revision ID: df64ffff8b33
Revises: 
Create Date: 2026-05-19 19:00:22.700315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df64ffff8b33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lastmile_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_ids', sa.JSON(), nullable=True),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_ids', sa.JSON(), nullable=True),
    sa.Column('country_ids', sa.JSON(), nullable=True),
    sa.Column('picking_rank', sa.Integer(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('date_last_refresh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slugs', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('seo_title', sa.JSON(), nullable=True),
    sa.Column('seo_description', sa.JSON(), nullable=True),
    sa.Column('category_description', sa.JSON(), nullable=True),
    sa.Column('subcategories', sa.JSON(), nullable=True),
    sa.Column('global_category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('global_category_parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lastmile_products',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraint_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_to_kg', sa.Float(), nullable=False),
    sa.Column('conversion_value', sa.Float(), nullable=False),
    sa.Column('country_of_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deposit_price', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('erp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_nutritions', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_fixed_weight', sa.Boolean(), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('last_month_lowest_price', sa.Float(), nullable=False),
    sa.Column('maximum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prc', sa.JSON(), nullable=True),
    sa.Column('cost_price', sa.JSON(), nullable=True),
    sa.Column('promo', sa.JSON(), nullable=True),
    sa.Column('promo_tags', sa.JSON(), nullable=True),
    sa.Column('slugs', sa.JSON(), nullable=True),
    sa.Column('standard_order_quantity', sa.Integer(), nullable=False),
    sa.Column('store_ids', sa.JSON(), nullable=True),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_weight', sa.Float(), nullable=False),
    sa.Column('name_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_lt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('storing_conditions', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('manufacturer_contact', sa.JSON(), nullable=True),
    sa.Column('safety_information', sa.JSON(), nullable=True),
    sa.Column('product_label', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comparative_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'store')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('lastmile_products')
    op.drop_table('lastmile_categories')
    # ### end Alembic commands ###
